on:
  workflow_call:
    inputs:
      jobIndex:
        description: "The requesting pipeline build number."
        required: true
        type: number
      parallelism:
        description: "The requesting pipeline build number."
        required: true
        default: 2
        type: number
      env:
        description: "Input environment."
        type: string
        default: '{}'
    secrets:
      token:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  job0:
    if: inputs.jobIndex < inputs.parallelism
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
  job1:
    needs: job0
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job2:
    needs: job1
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job3:
    needs: job2
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job4:
    needs: job3
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job5:
    needs: job4
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job6:
    needs: job5
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job7:
    needs: job6
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job8:
    needs: job7
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}
  job9:
    needs: job8
    if: contains(needs.*.outputs.hasmorejobs, 'true')
    uses: ./.github/workflows/run-with-agents.job.yml
    with:
      env: ${{ inputs.env }}
      message: ${{ toJSON(contains(needs.*.outputs.hasmorejobs, 'true')) }}